sudo: required

os:
 - linux

language: python

python:
 - "2.7.13"
 
services:
 - mariadb
 - docker

install:
 - pip install -r requirements.txt
 
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS votaciones_splc'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS votaciones_splc;'  
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/01_splc2017_programa.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/02_script_create_votaciones_splc.sql
  - mysql -u root --default-character-set=utf8 votaciones_splc < db_dump/03_script_populate_votaciones_splc.sql
 
script:
 - python recuento/tests.py

branches:
  - develop
  - master
