sudo: required

os:
 - linux

language: python

python:
 - "2.7.13"
 
services:
 - mariadb
 - docker

install:
 - pip install -r requirements.txt
 
script:
 - python recuento/tests.py

branches:
  - develop
  - master
