# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPerVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('optional', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('question_option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recuento.QuestionOption')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('0', ' WEB'), ('1', 'SLACK'), ('2', 'TELEGRAM')], max_length=1)),
                ('token', models.CharField(max_length=50)),
                ('question_options', models.ManyToManyField(through='recuento.OptionPerVote', to='recuento.QuestionOption')),
            ],
        ),
        migrations.AddField(
            model_name='optionpervote',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.QuestionOption'),
        ),
        migrations.AddField(
            model_name='optionpervote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuento.Vote'),
        ),
    ]
